# Generated by Django 2.1 on 2018-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_lng',
            field=models.FloatField(null=True),
        ),
    ]
