# Generated by Django 2.1 on 2018-10-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_auto_20181004_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_loc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_loc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
