# Generated by Django 2.1 on 2018-10-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0003_auto_20181005_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='address',
            field=models.CharField(default='Vallendar, Deutschland', max_length=255),
        ),
    ]
